### PR TITLE
added sphinx documentation

### PR DESCRIPTION
**Pull request by SteffenHaeussler**
https://github.com/diogomatoschaves/pyturf/issues/25

Hey, have a look, if this is for a first draft okay. 

Please make sure that:

- [x] You have read [CONTRIBUTING.md](../CONTRIBUTING.md)
- [x] You Include a link to the issue this pull request is associated to.
- [x] The linter has been run at the root level of the project: `black .`
- [x] All tests are passing: `python -m pytest --verbose --cov=./` 
- [x] Your branch is up to date with master: `git rebase upstream/master`

For new modules, also make sure that:

- [ ] The new module function is exported in `turf/<your-module>/__init__.py` and `turf/__init__.py`.
- [ ] The new module has been added under the `Available Modules` section on the [README](../README.md).

### CODE REVIEW

**Comment by diogomatoschaves** [comment]
The nearest-point and point-on-feature changes are also appearing in this PR. Can you rebase your branch from master so that those duplicates disappear?

**Comment by SteffenHaeussler** [comment]
as i mentioned, above, it is a first draft. I wait for the merge request [#29](https://github.com/diogomatoschaves/pyturf/pull/29) before i will rebase the branch.

**Comment by diogomatoschaves** [comment]
Ok sounds good. But I think it's good to go as a first implementation of the docs.

**Comment by SteffenHaeussler** [comment]
okay, i updated the docs with the latest additions to pyturf. let's figure out, how to host the html files. :)

**Pull request merged**
